### ISSUE TITLE
Access Violation on Parse.

### ISSUE THREAD

**Issue by AdriaanBoshoff** [thomaserlang/delphi-json#10]
Hi, Is there a reason that this might cause an access violation?
Note: I have changed the object names from `TJSON` to `TdJSON` to avoid conflicts with json writers.
```pascal
function IsValidLicense(const aLicense: string): Boolean;
var
  http: TIdHTTP;
  jdata: TdJSON;
begin
  http := TIdHTTP.Create(nil);
  try
    jdata.Parse(http.Get('http://qs.quantumsoftware.co.za:7777/rsm/license?key=' + aLicense));
    try
      Result := jdata['valid'].AsBoolean;
    finally
      jdata.Free;
    end;
  finally
    http.Free;
  end;
end;
```
This is the json response:
```json
{
  "valid": true,
  "message": "Product key is valid!"
}
```

**Comment by tobya** [comment]
It looks to me like jdata doesnt exist

**Comment by AdriaanBoshoff** [comment]
omw I'm stupid. I only see now I'm never actually creating it. This is what happens when you code at 3am. Thanks for the hint hahaha.
