### ISSUE TITLE
Handling null value

### ISSUE THREAD

**Issue by cdsaenz** [thomaserlang/delphi-json#16]
I have this response from a REST API:

```
{
   "status": true,
   "result": "OK",
   "json" :  {
	      "last_name": "Wilson"	
	    }
}

```

That sometimes brings an empty "json" element.. as null:

```
{
   "status": true,
   "result": "ERROR",
   "json" : null
}
```

And the code that I use is something like this. Works perfect in the first case, but fails when "json" has a null value.. How can I trap that error? I tried Assigned, nil, VarIsNull, etc but always get a violation.

Must be something simple but escapes me - Thanks for your help and this great utility.

```
JResp             := TdJSON.Parse(Content);
JResult           := JResp['result'].AsString;

if ( JResp['json'] <> nil ) then begin
      UserLast := JResp['json']['last_name'].AsString;
end;
```

**Comment by cdsaenz** [comment]
I think I found it!

`if ( JResp['json'].IsList )`

seems to do the job!

**Comment by cdsaenz** [comment]
After investigating.. I think this code will do?

`if ( Assigned(JResp['json'].Items) ) then begin`

**Comment by thomaserlang** [comment]
You can do:

```delphi
if (JResp['json'] <> null) then
```
Since the values are stored as variants.

**Comment by thomaserlang** [comment]
Just added IsNull.

```delphi
if (not JResp['json'].IsNull) then
```

**Comment by cdsaenz** [comment]
Thanks! works perfect! This unit is a real timesaver.
