### ISSUE TITLE
Key improvement

### ISSUE THREAD

**Issue by anders0nmat** [thomaserlang/delphi-json#18]
Hi, i just wanted to say, that i love this API. 

Besides I added support for fast Path description, idk how to describe it.
I made that instead of this
`dJSONObj['items']['part']['snippet']['url'].asString`
you can write this
`dJSONObj['items|part|snippet|url'].asString`

I am not sure if this is useful but it made my life easier.

**Comment by thomaserlang** [comment]
Glad to hear.

Interesting idea, pull requests are welcome.

**Comment by anders0nmat** [comment]
ok, maybe you guys have to improve my code, i wrote it in a hurry.

**Comment by thomaserlang** [comment]
https://github.com/thomaserlang/delphi-json/pull/19
