### ISSUE TITLE
Bug with empty value pair

### ISSUE THREAD

**Issue by raholland79** [thomaserlang/delphi-json#3]
If I have the following, I get an access violation that I can't properly figure

"Key": {} is the issue.

This is coming from a major financial API that I can't control, no idea why they're bringing blank hashes over.

```
{
  "QueryResponse":
  {
    "Item":
    [
     {
        "ItemGroupDetail": {},
        "Name":"Advance"
      }
]}}

```

Taking the `ItemGroupDetail `out or not having any values after `ItemGroupDetail` clears the issue.

**Comment by thomaserlang** [comment]
This should be fixed with commit 88318a7d529d3ab4bb5d1d3cba6e0aab1445340e
