### ISSUE TITLE
Crash on trying to parse 3 items.

### ISSUE THREAD

**Issue by AdriaanBoshoff** [thomaserlang/delphi-json#6]
So it seems when I try to parse this it works fine but as soon as there are 3 players it just gives me an access violation. Any reason why?
```
[
  {
    "SteamID": "removed",
    "OwnerSteamID": "0",
    "DisplayName": "removed",
    "Ping": 200,
    "Address": "removed",
    "ConnectedSeconds": 6386,
    "VoiationLevel": 0.0,
    "CurrentLevel": 0.0,
    "UnspentXp": 0.0,
    "Health": 97.70907
  },
  {
    "SteamID": "removed",
    "OwnerSteamID": "0",
    "DisplayName": "removed",
    "Ping": 264,
    "Address": "removed",
    "ConnectedSeconds": 3882,
    "VoiationLevel": 0.0,
    "CurrentLevel": 0.0,
    "UnspentXp": 0.0,
    "Health": 100.0
  }
]
```

My parse code:
```pascal
procedure Tfrmmain.GetPlayers(Data: string);
var
  users, user: TJSON;
  item: TListItem;
begin
  users := TJSON.Parse(Data);
  try
    for user in users do
    begin
      item := listViewPlayers.Items.Add;
      item.Caption := user['SteamID'].AsString;
      item.SubItems.Add(user['ConnectedSeconds'].AsString + ' Seconds');
      item.SubItems.Add(user['DisplayName'].AsString);
      item.SubItems.Add(user['Ping'].AsString);
      item.SubItems.Add(user['Address'].AsString);
      item.SubItems.Add(user['Health'].AsString);
    end;

  finally
    users.Free;
  end;
end;
```
EDIT: Is it possible that the string that it tries to parse is to long?

**Comment by thomaserlang** [comment]
I have tried to replicate your error without any success.
Does the attached json fail? If not please send what fails.
Also please attach where in the code the exception occurs and a stacktrace if available.

It should not be the size of the string. That's way too little text to even consider it a problem.

**Comment by AdriaanBoshoff** [comment]
Here is a msg fromt he debugger: https://i.imgur.com/KlkhpyZ.png and https://i.imgur.com/A7OXZHV.png

**Comment by AdriaanBoshoff** [comment]
It seems to only happen after it runs this: ```item.SubItems.Add(user['Health'].AsString);```

**Comment by thomaserlang** [comment]
So this is interesting. Your code works on my machine.
Have you checked that you run the latest version of djson.pas?

I would recommend that you install [madexcept](http://www.madshi.net/madExceptDescription.htm).
It'll give you a usable stacktrace, making it easier to debug these access violations.

**Comment by AdriaanBoshoff** [comment]
Thanks will do. I have a really big project that i started back in mod 2017. Started with rad studio 10.1.1 and now the latest. I've had a huge amount of issues lately. I'm thinking of just starting the project over amd copy / pasting the code.
